### ISSUE TITLE
Some types can't be generalized

### ISSUE THREAD

**Issue by rolandpeelen** [ambientlight/reductive-dev-tools#6]
I've recently updated to the latest version. When I use the new example code with my (previously working code), I get the following;

code: 
```typescript
let storeCreator = 
  ReductiveDevTools.Connectors.enhancer(
    ~options=ReductiveDevTools.Extension.enhancerOptions(
      ~name=__MODULE__, 
      ~actionCreators={
        "actionYouCanDispatchFromMonitor": (value: int) => `YourActionOfChoice(value)
          |. ReductiveDevTools.Utilities.Serializer.serializeAction
      },
      ()),
    ~devToolsUpdateActionCreator=(devToolsState) => `DevToolsUpdate(devToolsState),
    ()
  ) 
  @@ Reductive.Store.create;

let appStore =
  storeCreator(
    ~reducer=Reducer.appReducer,
    ~preloadedState=State.appBaseState,
    (),
  );
```
Error
```typescript
This has type:
    (Frontend.State.appState, Frontend.Actions.appAction) =>
    Frontend.State.appState
  But somewhere wanted:
    ReductiveDevTools.Types.reducer(([> `DevToolsUpdate(Frontend.State.appState) ]
                                     as 'a), Frontend.State.appState)
      (defined as Frontend     (Frontend.State.appState, 'a) => Frontend.State.appState)

  The incompatible parts:
    Frontend.Actions.appAction (defined as
      Frontend.Actions.appAction)
    vs
    'a
```

When I put in just the new example code but just the plain old `Reductive.Store.create`, I get the following error:
```typescript
This expression's type contains type variables that can't be generalized:
  ReductiveDevTools.Types.storeCreator(_[> `DevToolsUpdate('_weak1) ],
                                        '_weak1)
```

Maybe I'm missing something completely obvious, but I can't seem to the new version to work

**Comment by ambientlight** [comment]
@rolandpeelen: 
How do your Frontend.Actions.appAction look like?
Is 

```
`DevToolsUpdate(Frontend.State.appState)
```

is included in `Frontend.Actions.appAction`?

The new required parameter `~devToolsUpdateActionCreator` was created to give an ability to construct the custom action for the case when the state update is dispatched from redux-dev-tools monitor. You can return an action with a variant constructor that belongs to Frontend.Actions.appAction that would pack the incoming state from the monitor. Please check if that helps and let me know, thanks!

**Comment by rolandpeelen** [comment]
@ambientlight - Thanks! Got it up and running again. Perhaps it's good to write a little migration guide to the new version? This change wasn't directly clear for me from the new readme :)

**Comment by ambientlight** [comment]
@rolandpeelen: thanks, certainly
