### ISSUE TITLE
Is using normal (non-poly) variants as actions possible?

### ISSUE THREAD

**Issue by TomiS** [ambientlight/reductive-dev-tools#8]
I'm assuming they would serialize as integers because of how bucklescript works, am I right?

The reason I'm asking is that originally I was using normal variants as actions in my app. I think I only managed to get this tool working after I changed my actions to be polyvariants (there was other tweaking around going on too, so not 100% sure). So before rolling back and trying again, I figured to ask if normal variants _should_ work?

**Comment by ambientlight** [comment]
non-polyvars work, but when as constructors, instead of `PlainAction`, I would use `PlainAction(unit)`.
When used without constructors, you are right, they will resolve to plain numbers.

**Comment by TomiS** [comment]
Ok, changed back to normal variants (with constructors) and they indeed work as well as polyvariants. It was because of some other reason why they didn't work earlier. Ah, I really love refactoring Reason code. It's so ridiculously fast to do. :) But I'm closing this one.
