### ISSUE TITLE
Actions not showing if there is another store in the view

### ISSUE THREAD

**Issue by TomiS** [ambientlight/reductive-dev-tools#9]
I noticed that this tool works for me only if the reductive store is the only store in the app (I think). So in the full app where I was running also the old redux store and both reductive and redux store providers were nested in the component tree, the actions from Reason side didn't show up at all. I think this might be an issue with how redux devtools is configured in the app with two stores, so while solving this is probably not in the scope of this library, I'm reporting this behavior here so that it's possible to consider mentioning this in the docs (after I or someone has confirmed the reason)

There is a mention about multiple stores in redux-devtools-extension here:
https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0
so I guess it should work somehow

**Comment by ambientlight** [comment]
@TomiS: I also use it with hybrid stores, and it works for me, even when dispatched to different stores, in auto-mode the redux-devtools-extension will switch between stores automatically, maybe this is specific to how the `reductive-devtools-extension` is configured? Can you share the small sample of how you create your store?

**Comment by TomiS** [comment]
Ok, finally got back to this. It was actually working just fine. I just didn't originally realize I need to change the observed store in the redux devtools dropdown selector. Duh...
